name: deploy-dispatch

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm ci
        run: npm ci

      - name: Build
        run: YEVIS_WEB_BASE=/${{ github.event.repository.name }}/ npm run build
        env:
          VITE_WF_REPO: ${{ github.event.inputs.wf-repository }}
          VITE_WF_REPO_GH_PAGES_BRANCH: ${{ github.event.inputs.gh-pages-branch }}
          VITE_TRS_ENDPOINT: ${{ github.event.inputs.trs-endpoint }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
